[package]
name = "genesis"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true
hl-core = { path = "../hl-core" }
hl-io = { path = "../hl-io" }