[package]
name = "rhex-craft"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
anyhow.workspace = true
serde_json.workspace = true
serde_bytes.workspace = true
hl-core = { path = "../hl-core" }
hl-io = { path = "../hl-io" }